import { writeFileSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

interface Recipe {
  title: string;
  dont: string;
  doLine: string;
  why: string;
}

const RECIPES: Recipe[] = [
  {
    title: "Styled text nodes",
    dont: "createText + set fontName + set fontSize manually — leaves text unbound to styles.",
    doLine: "PluginOS.createStyledText({ characters, textStyleId, fillStyleId, name })",
    why: "load-font + create + bind-style + set-fill in one async call.",
  },
  {
    title: "Spacing variable bindings",
    dont: "setBoundVariable per padding field — 5 lines per frame.",
    doLine: "PluginOS.bindSpacing(node, { padding: spacingVar, itemSpacing: spacingVar })",
    why: "binds all 4 padding fields + itemSpacing in one call. paddingX/Y/specific keys win over `padding`.",
  },
  {
    title: "Variant sets",
    dont: "combineAsVariants then manually set layoutMode, wrap, sizing — variants stack at (0,0).",
    doLine: "PluginOS.combineAsVariantsTiled(cells, parent, { cols, gutter })",
    why: "applies HORIZONTAL + WRAP + FIXED width so variants render tiled instead of stacked.",
  },
  {
    title: "Top-level placement",
    dont: "figma.createComponent() in a loop — every node lands at (0,0) and overlaps.",
    doLine:
      "const place = PluginOS.tileTopLevel(figma.currentPage, { cols, gutter }); place(node);",
    why: "maintains a placement cursor across a single execute_figma call.",
  },
  {
    title: "SPACE_BETWEEN auto-layout",
    dont: 'frame.itemSpacing = "AUTO" — runtime-rejected. primaryAxisAlignItems = "SPACE_BETWEEN" collapses on inspect.',
    doLine: "PluginOS.layoutSpaceBetween(frame, { growChild })",
    why: "sets primaryAxisAlignItems = MIN and gives the grow target layoutGrow=1 (or layoutSizingHorizontal=FILL for TEXT).",
  },
];

export function generateRecipesSection(): string {
  const intro = `## Recipes for bulk-seed scripts

These helpers are available inside every \`execute_figma\` script. They prevent the most common bulk-seed bugs.
`;
  const body = RECIPES.map(
    (r) => `### ${r.title}
Don't: ${r.dont}
Do:    ${r.doLine}
Why:   ${r.why}
`
  ).join("\n");
  return intro + "\n" + body;
}

const MARKER_START = "<!-- AUTOGENERATED: recipes -->";
const MARKER_END = "<!-- /AUTOGENERATED: recipes -->";

export function applyRecipes(skillContent: string, recipes: string): string {
  const block = `${MARKER_START}\n${recipes}\n${MARKER_END}`;
  if (skillContent.includes(MARKER_START) && skillContent.includes(MARKER_END)) {
    return skillContent.replace(new RegExp(`${MARKER_START}[\\s\\S]*?${MARKER_END}`), block);
  }
  return `${skillContent.trimEnd()}\n\n${block}\n`;
}

function main(): void {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const path = resolve(__dirname, "..", "skills", "pluginos-figma", "SKILL.md");
  const before = readFileSync(path, "utf8");
  const after = applyRecipes(before, generateRecipesSection());
  if (before !== after) {
    writeFileSync(path, after);
    console.warn("sync-recipes: updated SKILL.md");
  } else {
    console.warn("sync-recipes: SKILL.md already in sync");
  }
}

const __filename = fileURLToPath(import.meta.url);
if (process.argv[1] && process.argv[1] === __filename) {
  main();
}
