import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

async function loadManifests() {
  process.env.PLUGINOS_SYNC = "1";
  (globalThis as any).figma = {
    mixed: Symbol("figma.mixed"),
    currentPage: { selection: [], findAll: () => [], children: [], name: "Stub" },
  };
  // Use absolute URL import so tsx resolves the same module graph for both the
  // side-effect op registrations and the listOperations function.
  const opsDir = resolve(__dirname, "../../bridge-plugin/src/operations");
  const indexMod = await import(pathToFileURL(resolve(opsDir, "index.ts")).href);
  return (indexMod.listOperations as () => any[])();
}

function render(manifests: any[]): string {
  const grouped: Record<string, any[]> = {};
  for (const m of manifests) {
    (grouped[m.category] ||= []).push(m);
  }
  const order = [
    "lint",
    "accessibility",
    "components",
    "tokens",
    "layout",
    "content",
    "export",
    "colors",
    "typography",
    "cleanup",
    "write",
    "custom",
  ];
  let out = `# PluginOS Operations Reference\n\n> Auto-generated by \`scripts/sync-ops.ts\`. Do not edit by hand.\n\n`;
  out += `Total operations: ${manifests.length}\n\n`;
  out += `| Op | Category | Default scope | Description |\n|---|---|---|---|\n`;
  for (const cat of order) {
    const list = grouped[cat];
    if (!list) continue;
    list.sort((a: any, b: any) => a.name.localeCompare(b.name));
    for (const op of list) {
      const ds = op.defaultScope || "page";
      out += `| \`${op.name}\` | ${op.category} | ${ds} | ${op.description.replace(/\|/g, "\\|")} |\n`;
    }
  }
  // Include any ops in categories not in `order` at the end (alphabetical by category)
  const leftover = Object.keys(grouped)
    .filter((c) => !order.includes(c))
    .sort();
  for (const cat of leftover) {
    const list = grouped[cat];
    list.sort((a: any, b: any) => a.name.localeCompare(b.name));
    for (const op of list) {
      const ds = op.defaultScope || "page";
      out += `| \`${op.name}\` | ${op.category} | ${ds} | ${op.description.replace(/\|/g, "\\|")} |\n`;
    }
  }
  return out;
}

(async () => {
  const manifests = await loadManifests();
  const md = render(manifests);
  const target = resolve(__dirname, "../skills/pluginos-figma/references/operations.md");
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, md);
  console.log(`Wrote ${manifests.length} ops to ${target}`);
})();
