import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(__dirname, "..");
const OPS_MD = resolve(ROOT, "skills/pluginos-figma/references/operations.md");

describe("operations.md (sync-ops output)", () => {
  it("exists", () => {
    expect(existsSync(OPS_MD)).toBe(true);
  });

  let content: string;
  let lines: string[];

  beforeAll(() => {
    content = readFileSync(OPS_MD, "utf-8");
    lines = content.split("\n");
  });

  it("starts with the expected header", () => {
    expect(content).toMatch(/^# PluginOS Operations Reference/);
  });

  it("contains the auto-generated notice", () => {
    expect(content).toContain("Auto-generated by `scripts/sync-ops.ts`");
    expect(content).toContain("Do not edit by hand");
  });

  it("has a total operations count line", () => {
    expect(content).toMatch(/^Total operations: \d+/m);
  });

  it("has at least 25 operations", () => {
    const match = content.match(/^Total operations: (\d+)/m);
    expect(match).not.toBeNull();
    const count = parseInt(match![1], 10);
    expect(count).toBeGreaterThanOrEqual(25);
  });

  it("has a markdown table with correct headers", () => {
    expect(content).toContain("| Op | Category | Default scope | Description |");
    expect(content).toContain("|---|---|---|---|");
  });

  it("includes lint operations", () => {
    expect(content).toContain("`lint_styles`");
    expect(content).toContain("`lint_detached`");
    expect(content).toContain("`lint_naming`");
  });

  it("includes accessibility operations", () => {
    expect(content).toContain("`check_contrast`");
    expect(content).toContain("`check_touch_targets`");
  });

  it("includes write/mutation operations", () => {
    expect(content).toContain("`create_frame`");
    expect(content).toContain("`set_fills`");
    expect(content).toContain("`set_text`");
    expect(content).toContain("`delete_node`");
    expect(content).toContain("`move_node`");
    expect(content).toContain("`resize_node`");
    expect(content).toContain("`clone_node`");
  });

  it("ops with selection default scope have 'selection' in default-scope column", () => {
    // lint_styles defaults to selection
    const lintStylesLine = lines.find((l) => l.includes("`lint_styles`"));
    expect(lintStylesLine).toBeDefined();
    expect(lintStylesLine).toContain("| selection |");
  });

  it("ops with page default scope have 'page' in default-scope column", () => {
    // export_tokens defaults to page
    const exportTokensLine = lines.find((l) => l.includes("`export_tokens`"));
    expect(exportTokensLine).toBeDefined();
    expect(exportTokensLine).toContain("| page |");
  });

  it("snapshot matches expected structure", () => {
    // Snapshot test — will auto-create on first run
    expect(content).toMatchSnapshot();
  });
});
